# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodelauditlogentry',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mymodelauditlogentry',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mymodelauditlogentry',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymodelauditlogentry',
            name='title_es',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
